/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 37.1.2 Mon Aug 22 10:27:11 2022.
 */

#include <string.h>

#include "mtlt305d.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int mtlt305d_request_pgn_pack(
    uint8_t *dst_p,
    const struct mtlt305d_request_pgn_t *src_p,
    size_t size)
{
    (void)src_p;

    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    return (3);
}

int mtlt305d_request_pgn_unpack(
    struct mtlt305d_request_pgn_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;

    if (size < 3u) {
        return (-EINVAL);
    }

    return (0);
}

int mtlt305d_aceinna_address_claiming_pack(
    uint8_t *dst_p,
    const struct mtlt305d_aceinna_address_claiming_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->j1939_name_arbitrary_address, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->j1939_name_industry_group, 1u, 0x0eu);
    dst_p[0] |= pack_left_shift_u8(src_p->j1939_name_vehicle_example, 4u, 0xf0u);
    dst_p[1] |= pack_left_shift_u8(src_p->j1939_name_vehicle_system, 0u, 0x7fu);
    dst_p[1] |= pack_left_shift_u8(src_p->j1939_name_reserved0, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->j1939_name_function, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->j1939_name_function_example, 0u, 0x1fu);
    dst_p[3] |= pack_left_shift_u8(src_p->j1939_name_ecu_example, 5u, 0xe0u);
    dst_p[4] |= pack_left_shift_u16(src_p->j1939_name_manufacture_code, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->j1939_name_manufacture_code, 8u, 0x07u);
    dst_p[5] |= pack_left_shift_u32(src_p->j1939_name_id_code, 3u, 0xf8u);
    dst_p[6] |= pack_right_shift_u32(src_p->j1939_name_id_code, 5u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->j1939_name_id_code, 13u, 0xffu);

    return (8);
}

int mtlt305d_aceinna_address_claiming_unpack(
    struct mtlt305d_aceinna_address_claiming_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->j1939_name_arbitrary_address = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->j1939_name_industry_group = unpack_right_shift_u8(src_p[0], 1u, 0x0eu);
    dst_p->j1939_name_vehicle_example = unpack_right_shift_u8(src_p[0], 4u, 0xf0u);
    dst_p->j1939_name_vehicle_system = unpack_right_shift_u8(src_p[1], 0u, 0x7fu);
    dst_p->j1939_name_reserved0 = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->j1939_name_function = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->j1939_name_function_example = unpack_right_shift_u8(src_p[3], 0u, 0x1fu);
    dst_p->j1939_name_ecu_example = unpack_right_shift_u8(src_p[3], 5u, 0xe0u);
    dst_p->j1939_name_manufacture_code = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->j1939_name_manufacture_code |= unpack_left_shift_u16(src_p[5], 8u, 0x07u);
    dst_p->j1939_name_id_code = unpack_right_shift_u32(src_p[5], 3u, 0xf8u);
    dst_p->j1939_name_id_code |= unpack_left_shift_u32(src_p[6], 5u, 0xffu);
    dst_p->j1939_name_id_code |= unpack_left_shift_u32(src_p[7], 13u, 0xffu);

    return (0);
}

uint8_t mtlt305d_aceinna_address_claiming_j1939_name_arbitrary_address_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_aceinna_address_claiming_j1939_name_arbitrary_address_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_address_claiming_j1939_name_arbitrary_address_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_aceinna_address_claiming_j1939_name_industry_group_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_aceinna_address_claiming_j1939_name_industry_group_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_address_claiming_j1939_name_industry_group_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t mtlt305d_aceinna_address_claiming_j1939_name_vehicle_example_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_aceinna_address_claiming_j1939_name_vehicle_example_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_address_claiming_j1939_name_vehicle_example_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t mtlt305d_aceinna_address_claiming_j1939_name_vehicle_system_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_aceinna_address_claiming_j1939_name_vehicle_system_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_address_claiming_j1939_name_vehicle_system_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

uint8_t mtlt305d_aceinna_address_claiming_j1939_name_reserved0_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_aceinna_address_claiming_j1939_name_reserved0_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_address_claiming_j1939_name_reserved0_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_aceinna_address_claiming_j1939_name_function_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_aceinna_address_claiming_j1939_name_function_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_address_claiming_j1939_name_function_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t mtlt305d_aceinna_address_claiming_j1939_name_function_example_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_aceinna_address_claiming_j1939_name_function_example_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_address_claiming_j1939_name_function_example_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

uint8_t mtlt305d_aceinna_address_claiming_j1939_name_ecu_example_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_aceinna_address_claiming_j1939_name_ecu_example_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_address_claiming_j1939_name_ecu_example_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint16_t mtlt305d_aceinna_address_claiming_j1939_name_manufacture_code_encode(double value)
{
    return (uint16_t)(value);
}

double mtlt305d_aceinna_address_claiming_j1939_name_manufacture_code_decode(uint16_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_address_claiming_j1939_name_manufacture_code_is_in_range(uint16_t value)
{
    return (value <= 2047u);
}

uint32_t mtlt305d_aceinna_address_claiming_j1939_name_id_code_encode(double value)
{
    return (uint32_t)(value);
}

double mtlt305d_aceinna_address_claiming_j1939_name_id_code_decode(uint32_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_address_claiming_j1939_name_id_code_is_in_range(uint32_t value)
{
    return (value <= 15u);
}

int mtlt305d_set_configuration_save_pack(
    uint8_t *dst_p,
    const struct mtlt305d_set_configuration_save_t *src_p,
    size_t size)
{
    uint8_t aceinna_failure_or_success;
    uint8_t aceinna_request_or_response;
    uint8_t aceinna_saved_address;

    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    aceinna_request_or_response = (uint8_t)src_p->aceinna_request_or_response;
    dst_p[0] |= pack_left_shift_u8(aceinna_request_or_response, 0u, 0xffu);
    aceinna_saved_address = (uint8_t)src_p->aceinna_saved_address;
    dst_p[1] |= pack_left_shift_u8(aceinna_saved_address, 0u, 0xffu);
    aceinna_failure_or_success = (uint8_t)src_p->aceinna_failure_or_success;
    dst_p[2] |= pack_left_shift_u8(aceinna_failure_or_success, 0u, 0xffu);

    return (3);
}

int mtlt305d_set_configuration_save_unpack(
    struct mtlt305d_set_configuration_save_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t aceinna_failure_or_success;
    uint8_t aceinna_request_or_response;
    uint8_t aceinna_saved_address;

    if (size < 3u) {
        return (-EINVAL);
    }

    aceinna_request_or_response = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->aceinna_request_or_response = (int8_t)aceinna_request_or_response;
    aceinna_saved_address = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->aceinna_saved_address = (int8_t)aceinna_saved_address;
    aceinna_failure_or_success = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->aceinna_failure_or_success = (int8_t)aceinna_failure_or_success;

    return (0);
}

int8_t mtlt305d_set_configuration_save_aceinna_request_or_response_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_configuration_save_aceinna_request_or_response_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_configuration_save_aceinna_request_or_response_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t mtlt305d_set_configuration_save_aceinna_saved_address_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_configuration_save_aceinna_saved_address_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_configuration_save_aceinna_saved_address_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t mtlt305d_set_configuration_save_aceinna_failure_or_success_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_configuration_save_aceinna_failure_or_success_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_configuration_save_aceinna_failure_or_success_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int mtlt305d_feedback_software_bit_pack(
    uint8_t *dst_p,
    const struct mtlt305d_feedback_software_bit_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->aceinna_sw_software_error, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->aceinna_sw_algorithm_error, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->aceinna_sw_data_error, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->aceinna_sw_initialization_error, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->aceinna_sw_over_range, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->aceinna_sw_calibration_crc_error, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u16(src_p->aceinna_sw_reserved0, 6u, 0xc0u);
    dst_p[1] |= pack_right_shift_u16(src_p->aceinna_sw_reserved0, 2u, 0xffu);

    return (2);
}

int mtlt305d_feedback_software_bit_unpack(
    struct mtlt305d_feedback_software_bit_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->aceinna_sw_software_error = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->aceinna_sw_algorithm_error = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->aceinna_sw_data_error = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->aceinna_sw_initialization_error = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->aceinna_sw_over_range = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->aceinna_sw_calibration_crc_error = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->aceinna_sw_reserved0 = unpack_right_shift_u16(src_p[0], 6u, 0xc0u);
    dst_p->aceinna_sw_reserved0 |= unpack_left_shift_u16(src_p[1], 2u, 0xffu);

    return (0);
}

uint8_t mtlt305d_feedback_software_bit_aceinna_sw_software_error_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_software_bit_aceinna_sw_software_error_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_software_bit_aceinna_sw_software_error_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_feedback_software_bit_aceinna_sw_algorithm_error_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_software_bit_aceinna_sw_algorithm_error_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_software_bit_aceinna_sw_algorithm_error_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_feedback_software_bit_aceinna_sw_data_error_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_software_bit_aceinna_sw_data_error_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_software_bit_aceinna_sw_data_error_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_feedback_software_bit_aceinna_sw_initialization_error_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_software_bit_aceinna_sw_initialization_error_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_software_bit_aceinna_sw_initialization_error_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_feedback_software_bit_aceinna_sw_over_range_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_software_bit_aceinna_sw_over_range_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_software_bit_aceinna_sw_over_range_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_feedback_software_bit_aceinna_sw_calibration_crc_error_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_software_bit_aceinna_sw_calibration_crc_error_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_software_bit_aceinna_sw_calibration_crc_error_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t mtlt305d_feedback_software_bit_aceinna_sw_reserved0_encode(double value)
{
    return (uint16_t)(value);
}

double mtlt305d_feedback_software_bit_aceinna_sw_reserved0_decode(uint16_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_software_bit_aceinna_sw_reserved0_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

int mtlt305d_feedback_hardware_bit_pack(
    uint8_t *dst_p,
    const struct mtlt305d_feedback_hardware_bit_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->aceinna_hw_master_fai, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->aceinna_hw_sensor_error, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->aceinna_hw_rate_error, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->aceinna_hw_accell_error, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u16(src_p->aceinna_hw_reserved0, 4u, 0xf0u);
    dst_p[1] |= pack_right_shift_u16(src_p->aceinna_hw_reserved0, 4u, 0xffu);

    return (2);
}

int mtlt305d_feedback_hardware_bit_unpack(
    struct mtlt305d_feedback_hardware_bit_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->aceinna_hw_master_fai = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->aceinna_hw_sensor_error = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->aceinna_hw_rate_error = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->aceinna_hw_accell_error = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->aceinna_hw_reserved0 = unpack_right_shift_u16(src_p[0], 4u, 0xf0u);
    dst_p->aceinna_hw_reserved0 |= unpack_left_shift_u16(src_p[1], 4u, 0xffu);

    return (0);
}

uint8_t mtlt305d_feedback_hardware_bit_aceinna_hw_master_fai_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_hardware_bit_aceinna_hw_master_fai_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_hardware_bit_aceinna_hw_master_fai_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_feedback_hardware_bit_aceinna_hw_sensor_error_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_hardware_bit_aceinna_hw_sensor_error_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_hardware_bit_aceinna_hw_sensor_error_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_feedback_hardware_bit_aceinna_hw_rate_error_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_hardware_bit_aceinna_hw_rate_error_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_hardware_bit_aceinna_hw_rate_error_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_feedback_hardware_bit_aceinna_hw_accell_error_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_hardware_bit_aceinna_hw_accell_error_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_hardware_bit_aceinna_hw_accell_error_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t mtlt305d_feedback_hardware_bit_aceinna_hw_reserved0_encode(double value)
{
    return (uint16_t)(value);
}

double mtlt305d_feedback_hardware_bit_aceinna_hw_reserved0_decode(uint16_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_hardware_bit_aceinna_hw_reserved0_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

int mtlt305d_feedback_ecu_id_pack(
    uint8_t *dst_p,
    const struct mtlt305d_feedback_ecu_id_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->j1939_name_arbitrary_address, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->j1939_name_industry_group, 1u, 0x0eu);
    dst_p[0] |= pack_left_shift_u8(src_p->j1939_name_vehicle_example, 4u, 0xf0u);
    dst_p[1] |= pack_left_shift_u8(src_p->j1939_name_vehicle_system, 0u, 0x7fu);
    dst_p[1] |= pack_left_shift_u8(src_p->j1939_name_reserved0, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->j1939_name_function, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->j1939_name_function_example, 0u, 0x1fu);
    dst_p[3] |= pack_left_shift_u8(src_p->j1939_name_ecu_example, 5u, 0xe0u);
    dst_p[4] |= pack_left_shift_u16(src_p->j1939_name_manufacture_code, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->j1939_name_manufacture_code, 8u, 0x07u);
    dst_p[5] |= pack_left_shift_u32(src_p->j1939_name_id_code, 3u, 0xf8u);
    dst_p[6] |= pack_right_shift_u32(src_p->j1939_name_id_code, 5u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->j1939_name_id_code, 13u, 0xffu);

    return (8);
}

int mtlt305d_feedback_ecu_id_unpack(
    struct mtlt305d_feedback_ecu_id_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->j1939_name_arbitrary_address = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->j1939_name_industry_group = unpack_right_shift_u8(src_p[0], 1u, 0x0eu);
    dst_p->j1939_name_vehicle_example = unpack_right_shift_u8(src_p[0], 4u, 0xf0u);
    dst_p->j1939_name_vehicle_system = unpack_right_shift_u8(src_p[1], 0u, 0x7fu);
    dst_p->j1939_name_reserved0 = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->j1939_name_function = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->j1939_name_function_example = unpack_right_shift_u8(src_p[3], 0u, 0x1fu);
    dst_p->j1939_name_ecu_example = unpack_right_shift_u8(src_p[3], 5u, 0xe0u);
    dst_p->j1939_name_manufacture_code = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->j1939_name_manufacture_code |= unpack_left_shift_u16(src_p[5], 8u, 0x07u);
    dst_p->j1939_name_id_code = unpack_right_shift_u32(src_p[5], 3u, 0xf8u);
    dst_p->j1939_name_id_code |= unpack_left_shift_u32(src_p[6], 5u, 0xffu);
    dst_p->j1939_name_id_code |= unpack_left_shift_u32(src_p[7], 13u, 0xffu);

    return (0);
}

uint8_t mtlt305d_feedback_ecu_id_j1939_name_arbitrary_address_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_ecu_id_j1939_name_arbitrary_address_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_ecu_id_j1939_name_arbitrary_address_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_feedback_ecu_id_j1939_name_industry_group_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_ecu_id_j1939_name_industry_group_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_ecu_id_j1939_name_industry_group_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t mtlt305d_feedback_ecu_id_j1939_name_vehicle_example_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_ecu_id_j1939_name_vehicle_example_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_ecu_id_j1939_name_vehicle_example_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t mtlt305d_feedback_ecu_id_j1939_name_vehicle_system_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_ecu_id_j1939_name_vehicle_system_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_ecu_id_j1939_name_vehicle_system_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

uint8_t mtlt305d_feedback_ecu_id_j1939_name_reserved0_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_ecu_id_j1939_name_reserved0_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_ecu_id_j1939_name_reserved0_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_feedback_ecu_id_j1939_name_function_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_ecu_id_j1939_name_function_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_ecu_id_j1939_name_function_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t mtlt305d_feedback_ecu_id_j1939_name_function_example_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_ecu_id_j1939_name_function_example_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_ecu_id_j1939_name_function_example_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

uint8_t mtlt305d_feedback_ecu_id_j1939_name_ecu_example_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_ecu_id_j1939_name_ecu_example_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_ecu_id_j1939_name_ecu_example_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint16_t mtlt305d_feedback_ecu_id_j1939_name_manufacture_code_encode(double value)
{
    return (uint16_t)(value);
}

double mtlt305d_feedback_ecu_id_j1939_name_manufacture_code_decode(uint16_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_ecu_id_j1939_name_manufacture_code_is_in_range(uint16_t value)
{
    return (value <= 2047u);
}

uint32_t mtlt305d_feedback_ecu_id_j1939_name_id_code_encode(double value)
{
    return (uint32_t)(value);
}

double mtlt305d_feedback_ecu_id_j1939_name_id_code_decode(uint32_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_ecu_id_j1939_name_id_code_is_in_range(uint32_t value)
{
    return (value <= 15u);
}

int mtlt305d_feedback_firmware_version_pack(
    uint8_t *dst_p,
    const struct mtlt305d_feedback_firmware_version_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->aceinna_firm_version_major, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->aceinna_firm_version_minor, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->aceinna_firm_version_patch, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->aceinna_firm_version_stage, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->aceinna_firm_version_build, 0u, 0xffu);

    return (5);
}

int mtlt305d_feedback_firmware_version_unpack(
    struct mtlt305d_feedback_firmware_version_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->aceinna_firm_version_major = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->aceinna_firm_version_minor = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->aceinna_firm_version_patch = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->aceinna_firm_version_stage = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->aceinna_firm_version_build = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

uint8_t mtlt305d_feedback_firmware_version_aceinna_firm_version_major_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_firmware_version_aceinna_firm_version_major_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_firmware_version_aceinna_firm_version_major_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t mtlt305d_feedback_firmware_version_aceinna_firm_version_minor_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_firmware_version_aceinna_firm_version_minor_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_firmware_version_aceinna_firm_version_minor_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t mtlt305d_feedback_firmware_version_aceinna_firm_version_patch_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_firmware_version_aceinna_firm_version_patch_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_firmware_version_aceinna_firm_version_patch_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t mtlt305d_feedback_firmware_version_aceinna_firm_version_stage_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_firmware_version_aceinna_firm_version_stage_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_firmware_version_aceinna_firm_version_stage_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t mtlt305d_feedback_firmware_version_aceinna_firm_version_build_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_firmware_version_aceinna_firm_version_build_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_firmware_version_aceinna_firm_version_build_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int mtlt305d_set_bank1_ps_num_pack(
    uint8_t *dst_p,
    const struct mtlt305d_set_bank1_ps_num_t *src_p,
    size_t size)
{
    uint8_t aceinna_ps_num_digital_filter;
    uint8_t aceinna_ps_num_orientation;
    uint8_t aceinna_ps_num_packet_rate;
    uint8_t aceinna_ps_num_type;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    aceinna_ps_num_packet_rate = (uint8_t)src_p->aceinna_ps_num_packet_rate;
    dst_p[0] |= pack_left_shift_u8(aceinna_ps_num_packet_rate, 0u, 0xffu);
    aceinna_ps_num_type = (uint8_t)src_p->aceinna_ps_num_type;
    dst_p[1] |= pack_left_shift_u8(aceinna_ps_num_type, 0u, 0xffu);
    aceinna_ps_num_digital_filter = (uint8_t)src_p->aceinna_ps_num_digital_filter;
    dst_p[2] |= pack_left_shift_u8(aceinna_ps_num_digital_filter, 0u, 0xffu);
    aceinna_ps_num_orientation = (uint8_t)src_p->aceinna_ps_num_orientation;
    dst_p[3] |= pack_left_shift_u8(aceinna_ps_num_orientation, 0u, 0xffu);

    return (8);
}

int mtlt305d_set_bank1_ps_num_unpack(
    struct mtlt305d_set_bank1_ps_num_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t aceinna_ps_num_digital_filter;
    uint8_t aceinna_ps_num_orientation;
    uint8_t aceinna_ps_num_packet_rate;
    uint8_t aceinna_ps_num_type;

    if (size < 8u) {
        return (-EINVAL);
    }

    aceinna_ps_num_packet_rate = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->aceinna_ps_num_packet_rate = (int8_t)aceinna_ps_num_packet_rate;
    aceinna_ps_num_type = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->aceinna_ps_num_type = (int8_t)aceinna_ps_num_type;
    aceinna_ps_num_digital_filter = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->aceinna_ps_num_digital_filter = (int8_t)aceinna_ps_num_digital_filter;
    aceinna_ps_num_orientation = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->aceinna_ps_num_orientation = (int8_t)aceinna_ps_num_orientation;

    return (0);
}

int8_t mtlt305d_set_bank1_ps_num_aceinna_ps_num_packet_rate_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_bank1_ps_num_aceinna_ps_num_packet_rate_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_bank1_ps_num_aceinna_ps_num_packet_rate_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t mtlt305d_set_bank1_ps_num_aceinna_ps_num_type_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_bank1_ps_num_aceinna_ps_num_type_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_bank1_ps_num_aceinna_ps_num_type_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t mtlt305d_set_bank1_ps_num_aceinna_ps_num_digital_filter_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_bank1_ps_num_aceinna_ps_num_digital_filter_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_bank1_ps_num_aceinna_ps_num_digital_filter_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t mtlt305d_set_bank1_ps_num_aceinna_ps_num_orientation_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_bank1_ps_num_aceinna_ps_num_orientation_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_bank1_ps_num_aceinna_ps_num_orientation_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int mtlt305d_set_bank0_ps_num_pack(
    uint8_t *dst_p,
    const struct mtlt305d_set_bank0_ps_num_t *src_p,
    size_t size)
{
    uint8_t aceinna_ps_num_algo_rest;
    uint8_t aceinna_ps_num_hw_bit;
    uint8_t aceinna_ps_num_status;
    uint8_t aceinna_ps_num_sw_bit;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    aceinna_ps_num_algo_rest = (uint8_t)src_p->aceinna_ps_num_algo_rest;
    dst_p[0] |= pack_left_shift_u8(aceinna_ps_num_algo_rest, 0u, 0xffu);
    aceinna_ps_num_hw_bit = (uint8_t)src_p->aceinna_ps_num_hw_bit;
    dst_p[2] |= pack_left_shift_u8(aceinna_ps_num_hw_bit, 0u, 0xffu);
    aceinna_ps_num_sw_bit = (uint8_t)src_p->aceinna_ps_num_sw_bit;
    dst_p[3] |= pack_left_shift_u8(aceinna_ps_num_sw_bit, 0u, 0xffu);
    aceinna_ps_num_status = (uint8_t)src_p->aceinna_ps_num_status;
    dst_p[4] |= pack_left_shift_u8(aceinna_ps_num_status, 0u, 0xffu);

    return (8);
}

int mtlt305d_set_bank0_ps_num_unpack(
    struct mtlt305d_set_bank0_ps_num_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t aceinna_ps_num_algo_rest;
    uint8_t aceinna_ps_num_hw_bit;
    uint8_t aceinna_ps_num_status;
    uint8_t aceinna_ps_num_sw_bit;

    if (size < 8u) {
        return (-EINVAL);
    }

    aceinna_ps_num_algo_rest = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->aceinna_ps_num_algo_rest = (int8_t)aceinna_ps_num_algo_rest;
    aceinna_ps_num_hw_bit = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->aceinna_ps_num_hw_bit = (int8_t)aceinna_ps_num_hw_bit;
    aceinna_ps_num_sw_bit = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->aceinna_ps_num_sw_bit = (int8_t)aceinna_ps_num_sw_bit;
    aceinna_ps_num_status = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->aceinna_ps_num_status = (int8_t)aceinna_ps_num_status;

    return (0);
}

int8_t mtlt305d_set_bank0_ps_num_aceinna_ps_num_algo_rest_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_bank0_ps_num_aceinna_ps_num_algo_rest_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_bank0_ps_num_aceinna_ps_num_algo_rest_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t mtlt305d_set_bank0_ps_num_aceinna_ps_num_hw_bit_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_bank0_ps_num_aceinna_ps_num_hw_bit_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_bank0_ps_num_aceinna_ps_num_hw_bit_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t mtlt305d_set_bank0_ps_num_aceinna_ps_num_sw_bit_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_bank0_ps_num_aceinna_ps_num_sw_bit_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_bank0_ps_num_aceinna_ps_num_sw_bit_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t mtlt305d_set_bank0_ps_num_aceinna_ps_num_status_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_bank0_ps_num_aceinna_ps_num_status_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_bank0_ps_num_aceinna_ps_num_status_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int mtlt305d_set_orientation_pack(
    uint8_t *dst_p,
    const struct mtlt305d_set_orientation_t *src_p,
    size_t size)
{
    uint16_t aceinna_new_orientation_type;
    uint8_t aceinna_destination_address;

    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    aceinna_destination_address = (uint8_t)src_p->aceinna_destination_address;
    dst_p[0] |= pack_left_shift_u8(aceinna_destination_address, 0u, 0xffu);
    aceinna_new_orientation_type = (uint16_t)src_p->aceinna_new_orientation_type;
    dst_p[1] |= pack_left_shift_u16(aceinna_new_orientation_type, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(aceinna_new_orientation_type, 8u, 0xffu);

    return (3);
}

int mtlt305d_set_orientation_unpack(
    struct mtlt305d_set_orientation_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t aceinna_new_orientation_type;
    uint8_t aceinna_destination_address;

    if (size < 3u) {
        return (-EINVAL);
    }

    aceinna_destination_address = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->aceinna_destination_address = (int8_t)aceinna_destination_address;
    aceinna_new_orientation_type = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    aceinna_new_orientation_type |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->aceinna_new_orientation_type = (int16_t)aceinna_new_orientation_type;

    return (0);
}

int8_t mtlt305d_set_orientation_aceinna_destination_address_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_orientation_aceinna_destination_address_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_orientation_aceinna_destination_address_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int16_t mtlt305d_set_orientation_aceinna_new_orientation_type_encode(double value)
{
    return (int16_t)(value);
}

double mtlt305d_set_orientation_aceinna_new_orientation_type_decode(int16_t value)
{
    return ((double)value);
}

bool mtlt305d_set_orientation_aceinna_new_orientation_type_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int mtlt305d_set_digital_filter_pack(
    uint8_t *dst_p,
    const struct mtlt305d_set_digital_filter_t *src_p,
    size_t size)
{
    uint8_t aceinna_destination_address;
    uint8_t aceinna_new_acc_low_pass;
    uint8_t aceinna_new_gyro_low_pass;

    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    aceinna_destination_address = (uint8_t)src_p->aceinna_destination_address;
    dst_p[0] |= pack_left_shift_u8(aceinna_destination_address, 0u, 0xffu);
    aceinna_new_gyro_low_pass = (uint8_t)src_p->aceinna_new_gyro_low_pass;
    dst_p[1] |= pack_left_shift_u8(aceinna_new_gyro_low_pass, 0u, 0xffu);
    aceinna_new_acc_low_pass = (uint8_t)src_p->aceinna_new_acc_low_pass;
    dst_p[2] |= pack_left_shift_u8(aceinna_new_acc_low_pass, 0u, 0xffu);

    return (3);
}

int mtlt305d_set_digital_filter_unpack(
    struct mtlt305d_set_digital_filter_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t aceinna_destination_address;
    uint8_t aceinna_new_acc_low_pass;
    uint8_t aceinna_new_gyro_low_pass;

    if (size < 3u) {
        return (-EINVAL);
    }

    aceinna_destination_address = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->aceinna_destination_address = (int8_t)aceinna_destination_address;
    aceinna_new_gyro_low_pass = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->aceinna_new_gyro_low_pass = (int8_t)aceinna_new_gyro_low_pass;
    aceinna_new_acc_low_pass = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->aceinna_new_acc_low_pass = (int8_t)aceinna_new_acc_low_pass;

    return (0);
}

int8_t mtlt305d_set_digital_filter_aceinna_destination_address_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_digital_filter_aceinna_destination_address_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_digital_filter_aceinna_destination_address_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t mtlt305d_set_digital_filter_aceinna_new_gyro_low_pass_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_digital_filter_aceinna_new_gyro_low_pass_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_digital_filter_aceinna_new_gyro_low_pass_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t mtlt305d_set_digital_filter_aceinna_new_acc_low_pass_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_digital_filter_aceinna_new_acc_low_pass_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_digital_filter_aceinna_new_acc_low_pass_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int mtlt305d_set_data_pcket_type_pack(
    uint8_t *dst_p,
    const struct mtlt305d_set_data_pcket_type_t *src_p,
    size_t size)
{
    uint8_t aceinna_destination_address;
    uint8_t aceinna_new_packet_type;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    aceinna_destination_address = (uint8_t)src_p->aceinna_destination_address;
    dst_p[0] |= pack_left_shift_u8(aceinna_destination_address, 0u, 0xffu);
    aceinna_new_packet_type = (uint8_t)src_p->aceinna_new_packet_type;
    dst_p[1] |= pack_left_shift_u8(aceinna_new_packet_type, 0u, 0xffu);

    return (2);
}

int mtlt305d_set_data_pcket_type_unpack(
    struct mtlt305d_set_data_pcket_type_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t aceinna_destination_address;
    uint8_t aceinna_new_packet_type;

    if (size < 2u) {
        return (-EINVAL);
    }

    aceinna_destination_address = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->aceinna_destination_address = (int8_t)aceinna_destination_address;
    aceinna_new_packet_type = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->aceinna_new_packet_type = (int8_t)aceinna_new_packet_type;

    return (0);
}

int8_t mtlt305d_set_data_pcket_type_aceinna_destination_address_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_data_pcket_type_aceinna_destination_address_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_data_pcket_type_aceinna_destination_address_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t mtlt305d_set_data_pcket_type_aceinna_new_packet_type_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_data_pcket_type_aceinna_new_packet_type_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_data_pcket_type_aceinna_new_packet_type_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int mtlt305d_set_packet_rate_divider_pack(
    uint8_t *dst_p,
    const struct mtlt305d_set_packet_rate_divider_t *src_p,
    size_t size)
{
    uint8_t aceinna_destination_address;
    uint8_t aceinna_new_pocket_rate;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    aceinna_destination_address = (uint8_t)src_p->aceinna_destination_address;
    dst_p[0] |= pack_left_shift_u8(aceinna_destination_address, 0u, 0xffu);
    aceinna_new_pocket_rate = (uint8_t)src_p->aceinna_new_pocket_rate;
    dst_p[1] |= pack_left_shift_u8(aceinna_new_pocket_rate, 0u, 0xffu);

    return (2);
}

int mtlt305d_set_packet_rate_divider_unpack(
    struct mtlt305d_set_packet_rate_divider_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t aceinna_destination_address;
    uint8_t aceinna_new_pocket_rate;

    if (size < 2u) {
        return (-EINVAL);
    }

    aceinna_destination_address = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->aceinna_destination_address = (int8_t)aceinna_destination_address;
    aceinna_new_pocket_rate = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->aceinna_new_pocket_rate = (int8_t)aceinna_new_pocket_rate;

    return (0);
}

int8_t mtlt305d_set_packet_rate_divider_aceinna_destination_address_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_packet_rate_divider_aceinna_destination_address_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_packet_rate_divider_aceinna_destination_address_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t mtlt305d_set_packet_rate_divider_aceinna_new_pocket_rate_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_packet_rate_divider_aceinna_new_pocket_rate_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_packet_rate_divider_aceinna_new_pocket_rate_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int mtlt305d_set_algorithm_reset_pack(
    uint8_t *dst_p,
    const struct mtlt305d_set_algorithm_reset_t *src_p,
    size_t size)
{
    uint8_t aceinna_failure_or_success;
    uint8_t aceinna_request_or_response;
    uint8_t aceinna_saved_address;

    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    aceinna_request_or_response = (uint8_t)src_p->aceinna_request_or_response;
    dst_p[0] |= pack_left_shift_u8(aceinna_request_or_response, 0u, 0xffu);
    aceinna_saved_address = (uint8_t)src_p->aceinna_saved_address;
    dst_p[1] |= pack_left_shift_u8(aceinna_saved_address, 0u, 0xffu);
    aceinna_failure_or_success = (uint8_t)src_p->aceinna_failure_or_success;
    dst_p[2] |= pack_left_shift_u8(aceinna_failure_or_success, 0u, 0xffu);

    return (3);
}

int mtlt305d_set_algorithm_reset_unpack(
    struct mtlt305d_set_algorithm_reset_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t aceinna_failure_or_success;
    uint8_t aceinna_request_or_response;
    uint8_t aceinna_saved_address;

    if (size < 3u) {
        return (-EINVAL);
    }

    aceinna_request_or_response = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->aceinna_request_or_response = (int8_t)aceinna_request_or_response;
    aceinna_saved_address = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->aceinna_saved_address = (int8_t)aceinna_saved_address;
    aceinna_failure_or_success = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->aceinna_failure_or_success = (int8_t)aceinna_failure_or_success;

    return (0);
}

int8_t mtlt305d_set_algorithm_reset_aceinna_request_or_response_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_algorithm_reset_aceinna_request_or_response_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_algorithm_reset_aceinna_request_or_response_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t mtlt305d_set_algorithm_reset_aceinna_saved_address_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_algorithm_reset_aceinna_saved_address_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_algorithm_reset_aceinna_saved_address_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t mtlt305d_set_algorithm_reset_aceinna_failure_or_success_encode(double value)
{
    return (int8_t)(value);
}

double mtlt305d_set_algorithm_reset_aceinna_failure_or_success_decode(int8_t value)
{
    return ((double)value);
}

bool mtlt305d_set_algorithm_reset_aceinna_failure_or_success_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int mtlt305d_feedback_configuration_save_pack(
    uint8_t *dst_p,
    const struct mtlt305d_feedback_configuration_save_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->aceinna_request_or_response, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->aceinna_saved_address, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->aceinna_failure_or_success, 0u, 0xffu);

    return (3);
}

int mtlt305d_feedback_configuration_save_unpack(
    struct mtlt305d_feedback_configuration_save_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->aceinna_request_or_response = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->aceinna_saved_address = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->aceinna_failure_or_success = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

uint8_t mtlt305d_feedback_configuration_save_aceinna_request_or_response_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_configuration_save_aceinna_request_or_response_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_configuration_save_aceinna_request_or_response_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t mtlt305d_feedback_configuration_save_aceinna_saved_address_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_configuration_save_aceinna_saved_address_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_configuration_save_aceinna_saved_address_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t mtlt305d_feedback_configuration_save_aceinna_failure_or_success_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_configuration_save_aceinna_failure_or_success_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_configuration_save_aceinna_failure_or_success_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int mtlt305d_feedback_sensor_status_pack(
    uint8_t *dst_p,
    const struct mtlt305d_feedback_sensor_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->aceinna_master_status, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->aceinna_hardware_status, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->aceinna_software_status, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->aceinna_sensor_status, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->aceinna_reserved0, 4u, 0x70u);
    dst_p[0] |= pack_left_shift_u8(src_p->aceinna_unlocked_eeprom, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->aceinna_algo_init, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->aceinna_reserved1, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->aceinna_attitude_only_algo, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->aceinna_turn_switch, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->aceinna_sensor_over_range, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->aceinna_reserved3, 5u, 0xe0u);

    return (8);
}

int mtlt305d_feedback_sensor_status_unpack(
    struct mtlt305d_feedback_sensor_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->aceinna_master_status = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->aceinna_hardware_status = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->aceinna_software_status = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->aceinna_sensor_status = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->aceinna_reserved0 = unpack_right_shift_u8(src_p[0], 4u, 0x70u);
    dst_p->aceinna_unlocked_eeprom = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->aceinna_algo_init = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->aceinna_reserved1 = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->aceinna_attitude_only_algo = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->aceinna_turn_switch = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->aceinna_sensor_over_range = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->aceinna_reserved3 = unpack_right_shift_u8(src_p[1], 5u, 0xe0u);

    return (0);
}

uint8_t mtlt305d_feedback_sensor_status_aceinna_master_status_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_sensor_status_aceinna_master_status_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_sensor_status_aceinna_master_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_feedback_sensor_status_aceinna_hardware_status_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_sensor_status_aceinna_hardware_status_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_sensor_status_aceinna_hardware_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_feedback_sensor_status_aceinna_software_status_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_sensor_status_aceinna_software_status_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_sensor_status_aceinna_software_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_feedback_sensor_status_aceinna_sensor_status_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_sensor_status_aceinna_sensor_status_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_sensor_status_aceinna_sensor_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_feedback_sensor_status_aceinna_reserved0_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_sensor_status_aceinna_reserved0_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_sensor_status_aceinna_reserved0_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t mtlt305d_feedback_sensor_status_aceinna_unlocked_eeprom_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_sensor_status_aceinna_unlocked_eeprom_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_sensor_status_aceinna_unlocked_eeprom_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_feedback_sensor_status_aceinna_algo_init_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_sensor_status_aceinna_algo_init_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_sensor_status_aceinna_algo_init_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_feedback_sensor_status_aceinna_reserved1_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_sensor_status_aceinna_reserved1_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_sensor_status_aceinna_reserved1_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t mtlt305d_feedback_sensor_status_aceinna_attitude_only_algo_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_sensor_status_aceinna_attitude_only_algo_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_sensor_status_aceinna_attitude_only_algo_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_feedback_sensor_status_aceinna_turn_switch_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_sensor_status_aceinna_turn_switch_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_sensor_status_aceinna_turn_switch_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_feedback_sensor_status_aceinna_sensor_over_range_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_sensor_status_aceinna_sensor_over_range_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_sensor_status_aceinna_sensor_over_range_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mtlt305d_feedback_sensor_status_aceinna_reserved3_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_feedback_sensor_status_aceinna_reserved3_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_feedback_sensor_status_aceinna_reserved3_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

int mtlt305d_aceinna_angle_rate_pack(
    uint8_t *dst_p,
    const struct mtlt305d_aceinna_angle_rate_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->aceinna_gyro_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->aceinna_gyro_x, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->aceinna_gyro_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->aceinna_gyro_y, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->aceinna_gyro_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->aceinna_gyro_z, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->aceinna_pitch_rate_figure_of_merit, 0u, 0x03u);
    dst_p[6] |= pack_left_shift_u8(src_p->aceinna_roll_rate_figure_of_merit, 2u, 0x0cu);
    dst_p[6] |= pack_left_shift_u8(src_p->aceinna_yaw_rate_figure_of_merit, 4u, 0x30u);
    dst_p[7] |= pack_left_shift_u8(src_p->aceinna_angle_rate_latency, 0u, 0xffu);

    return (8);
}

int mtlt305d_aceinna_angle_rate_unpack(
    struct mtlt305d_aceinna_angle_rate_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->aceinna_gyro_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->aceinna_gyro_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->aceinna_gyro_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->aceinna_gyro_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->aceinna_gyro_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->aceinna_gyro_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->aceinna_pitch_rate_figure_of_merit = unpack_right_shift_u8(src_p[6], 0u, 0x03u);
    dst_p->aceinna_roll_rate_figure_of_merit = unpack_right_shift_u8(src_p[6], 2u, 0x0cu);
    dst_p->aceinna_yaw_rate_figure_of_merit = unpack_right_shift_u8(src_p[6], 4u, 0x30u);
    dst_p->aceinna_angle_rate_latency = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint16_t mtlt305d_aceinna_angle_rate_aceinna_gyro_x_encode(double value)
{
    return (uint16_t)((value - -250.0) / 0.0078125);
}

double mtlt305d_aceinna_angle_rate_aceinna_gyro_x_decode(uint16_t value)
{
    return (((double)value * 0.0078125) + -250.0);
}

bool mtlt305d_aceinna_angle_rate_aceinna_gyro_x_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t mtlt305d_aceinna_angle_rate_aceinna_gyro_y_encode(double value)
{
    return (uint16_t)((value - -250.0) / 0.0078125);
}

double mtlt305d_aceinna_angle_rate_aceinna_gyro_y_decode(uint16_t value)
{
    return (((double)value * 0.0078125) + -250.0);
}

bool mtlt305d_aceinna_angle_rate_aceinna_gyro_y_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t mtlt305d_aceinna_angle_rate_aceinna_gyro_z_encode(double value)
{
    return (uint16_t)((value - -250.0) / 0.0078125);
}

double mtlt305d_aceinna_angle_rate_aceinna_gyro_z_decode(uint16_t value)
{
    return (((double)value * 0.0078125) + -250.0);
}

bool mtlt305d_aceinna_angle_rate_aceinna_gyro_z_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t mtlt305d_aceinna_angle_rate_aceinna_pitch_rate_figure_of_merit_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_aceinna_angle_rate_aceinna_pitch_rate_figure_of_merit_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_angle_rate_aceinna_pitch_rate_figure_of_merit_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t mtlt305d_aceinna_angle_rate_aceinna_roll_rate_figure_of_merit_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_aceinna_angle_rate_aceinna_roll_rate_figure_of_merit_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_angle_rate_aceinna_roll_rate_figure_of_merit_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t mtlt305d_aceinna_angle_rate_aceinna_yaw_rate_figure_of_merit_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_aceinna_angle_rate_aceinna_yaw_rate_figure_of_merit_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_angle_rate_aceinna_yaw_rate_figure_of_merit_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t mtlt305d_aceinna_angle_rate_aceinna_angle_rate_latency_encode(double value)
{
    return (uint8_t)(value / 0.5);
}

double mtlt305d_aceinna_angle_rate_aceinna_angle_rate_latency_decode(uint8_t value)
{
    return ((double)value * 0.5);
}

bool mtlt305d_aceinna_angle_rate_aceinna_angle_rate_latency_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int mtlt305d_aceinna_accel_pack(
    uint8_t *dst_p,
    const struct mtlt305d_aceinna_accel_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->aceinna_acc_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->aceinna_acc_x, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->aceinna_acc_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->aceinna_acc_y, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->aceinna_acc_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->aceinna_acc_z, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->aceinna_lateral_acc_figure_of_merit, 0u, 0x03u);
    dst_p[6] |= pack_left_shift_u8(src_p->aceinna_longi_acc_figure_of_merit, 2u, 0x0cu);
    dst_p[6] |= pack_left_shift_u8(src_p->aceinna_vertic_acc_figure_of_merit, 4u, 0x30u);
    dst_p[6] |= pack_left_shift_u8(src_p->aceinna_support_rate_acc, 6u, 0xc0u);

    return (8);
}

int mtlt305d_aceinna_accel_unpack(
    struct mtlt305d_aceinna_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->aceinna_acc_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->aceinna_acc_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->aceinna_acc_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->aceinna_acc_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->aceinna_acc_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->aceinna_acc_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->aceinna_lateral_acc_figure_of_merit = unpack_right_shift_u8(src_p[6], 0u, 0x03u);
    dst_p->aceinna_longi_acc_figure_of_merit = unpack_right_shift_u8(src_p[6], 2u, 0x0cu);
    dst_p->aceinna_vertic_acc_figure_of_merit = unpack_right_shift_u8(src_p[6], 4u, 0x30u);
    dst_p->aceinna_support_rate_acc = unpack_right_shift_u8(src_p[6], 6u, 0xc0u);

    return (0);
}

uint16_t mtlt305d_aceinna_accel_aceinna_acc_x_encode(double value)
{
    return (uint16_t)((value - -320.0) / 0.01);
}

double mtlt305d_aceinna_accel_aceinna_acc_x_decode(uint16_t value)
{
    return (((double)value * 0.01) + -320.0);
}

bool mtlt305d_aceinna_accel_aceinna_acc_x_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t mtlt305d_aceinna_accel_aceinna_acc_y_encode(double value)
{
    return (uint16_t)((value - -320.0) / 0.01);
}

double mtlt305d_aceinna_accel_aceinna_acc_y_decode(uint16_t value)
{
    return (((double)value * 0.01) + -320.0);
}

bool mtlt305d_aceinna_accel_aceinna_acc_y_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t mtlt305d_aceinna_accel_aceinna_acc_z_encode(double value)
{
    return (uint16_t)((value - -320.0) / 0.01);
}

double mtlt305d_aceinna_accel_aceinna_acc_z_decode(uint16_t value)
{
    return (((double)value * 0.01) + -320.0);
}

bool mtlt305d_aceinna_accel_aceinna_acc_z_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t mtlt305d_aceinna_accel_aceinna_lateral_acc_figure_of_merit_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_aceinna_accel_aceinna_lateral_acc_figure_of_merit_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_accel_aceinna_lateral_acc_figure_of_merit_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t mtlt305d_aceinna_accel_aceinna_longi_acc_figure_of_merit_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_aceinna_accel_aceinna_longi_acc_figure_of_merit_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_accel_aceinna_longi_acc_figure_of_merit_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t mtlt305d_aceinna_accel_aceinna_vertic_acc_figure_of_merit_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_aceinna_accel_aceinna_vertic_acc_figure_of_merit_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_accel_aceinna_vertic_acc_figure_of_merit_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t mtlt305d_aceinna_accel_aceinna_support_rate_acc_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_aceinna_accel_aceinna_support_rate_acc_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_accel_aceinna_support_rate_acc_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int mtlt305d_aceinna_angles_pack(
    uint8_t *dst_p,
    const struct mtlt305d_aceinna_angles_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->aceinna_pitch, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->aceinna_pitch, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->aceinna_pitch, 16u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(src_p->aceinna_roll, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->aceinna_roll, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->aceinna_roll, 16u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->aceinna_pitch_compensation, 0u, 0x03u);
    dst_p[6] |= pack_left_shift_u8(src_p->aceinna_pitch_figure_of_merit, 2u, 0x0cu);
    dst_p[6] |= pack_left_shift_u8(src_p->aceinna_roll_compensation, 4u, 0x30u);
    dst_p[6] |= pack_left_shift_u8(src_p->aceinna_roll_figure_of_merit, 6u, 0xc0u);
    dst_p[7] |= pack_left_shift_u8(src_p->aceinna_pitch_roll_latency, 0u, 0xffu);

    return (8);
}

int mtlt305d_aceinna_angles_unpack(
    struct mtlt305d_aceinna_angles_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->aceinna_pitch = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->aceinna_pitch |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->aceinna_pitch |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->aceinna_roll = unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->aceinna_roll |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
    dst_p->aceinna_roll |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);
    dst_p->aceinna_pitch_compensation = unpack_right_shift_u8(src_p[6], 0u, 0x03u);
    dst_p->aceinna_pitch_figure_of_merit = unpack_right_shift_u8(src_p[6], 2u, 0x0cu);
    dst_p->aceinna_roll_compensation = unpack_right_shift_u8(src_p[6], 4u, 0x30u);
    dst_p->aceinna_roll_figure_of_merit = unpack_right_shift_u8(src_p[6], 6u, 0xc0u);
    dst_p->aceinna_pitch_roll_latency = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint32_t mtlt305d_aceinna_angles_aceinna_pitch_encode(double value)
{
    return (uint32_t)((value - -250.0) / 0.000030517578125);
}

double mtlt305d_aceinna_angles_aceinna_pitch_decode(uint32_t value)
{
    return (((double)value * 0.000030517578125) + -250.0);
}

bool mtlt305d_aceinna_angles_aceinna_pitch_is_in_range(uint32_t value)
{
    return (value <= 16449536u);
}

uint32_t mtlt305d_aceinna_angles_aceinna_roll_encode(double value)
{
    return (uint32_t)((value - -250.0) / 0.000030517578125);
}

double mtlt305d_aceinna_angles_aceinna_roll_decode(uint32_t value)
{
    return (((double)value * 0.000030517578125) + -250.0);
}

bool mtlt305d_aceinna_angles_aceinna_roll_is_in_range(uint32_t value)
{
    return (value <= 16449536u);
}

uint8_t mtlt305d_aceinna_angles_aceinna_pitch_compensation_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_aceinna_angles_aceinna_pitch_compensation_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_angles_aceinna_pitch_compensation_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t mtlt305d_aceinna_angles_aceinna_pitch_figure_of_merit_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_aceinna_angles_aceinna_pitch_figure_of_merit_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_angles_aceinna_pitch_figure_of_merit_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t mtlt305d_aceinna_angles_aceinna_roll_compensation_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_aceinna_angles_aceinna_roll_compensation_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_angles_aceinna_roll_compensation_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t mtlt305d_aceinna_angles_aceinna_roll_figure_of_merit_encode(double value)
{
    return (uint8_t)(value);
}

double mtlt305d_aceinna_angles_aceinna_roll_figure_of_merit_decode(uint8_t value)
{
    return ((double)value);
}

bool mtlt305d_aceinna_angles_aceinna_roll_figure_of_merit_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t mtlt305d_aceinna_angles_aceinna_pitch_roll_latency_encode(double value)
{
    return (uint8_t)(value / 0.5);
}

double mtlt305d_aceinna_angles_aceinna_pitch_roll_latency_decode(uint8_t value)
{
    return ((double)value * 0.5);
}

bool mtlt305d_aceinna_angles_aceinna_pitch_roll_latency_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}
