[workspace]
members = [
    "play_args", 
    "play_hello", 
    "play_println", 
    "play_thread", 
    "play_mpsc", 
    "play_udp",
    "play_serial",
    "play_serial2",
    "play_can",
    "play_canfd",
]